# Generated by Django 3.2.9 on 2022-04-15 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocketProceeding_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mag_num', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='date of court session')),
                ('judge', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=5000)),
                ('bond_set_for', models.FloatField(blank=True, null=True)),
                ('mag_section', models.CharField(default='', max_length=2)),
                ('docket_charges', models.ManyToManyField(to='website.DocketCharge')),
            ],
        ),
        migrations.CreateModel(
            name='Question_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.BigIntegerField()),
                ('question_text', models.CharField(max_length=600)),
                ('question_type', models.CharField(max_length=30)),
                ('question_subtype', models.CharField(max_length=30)),
                ('question_clean_text', models.CharField(default='', max_length=600)),
                ('cluster_id', models.IntegerField(default=-1)),
                ('survey', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Response_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_id', models.BigIntegerField()),
                ('collector_id', models.BigIntegerField()),
                ('response_text', models.CharField(max_length=5000)),
                ('row_id', models.BigIntegerField(default=0)),
                ('choice_id', models.BigIntegerField()),
                ('other_id', models.BigIntegerField()),
                ('choice_text', models.CharField(max_length=200)),
                ('choice_clean_text', models.CharField(default='', max_length=200)),
                ('question', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.question_new')),
                ('survey', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.survey')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='survey',
        ),
        migrations.DeleteModel(
            name='DocketProceeding',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AlterField(
            model_name='responseoptions',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.question_new'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
