# Generated by Django 3.2.9 on 2022-02-02 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_greeting_when'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
