# Generated by Django 4.0.2 on 2022-03-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_question_cluster_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='docketproceeding',
            name='bond_set_for',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docketproceeding',
            name='docket_charges',
            field=models.ManyToManyField(to='website.DocketCharge'),
        ),
        migrations.AlterField(
            model_name='docketproceeding',
            name='mag_num',
            field=models.IntegerField(),
        ),
    ]
