# Generated by Django 3.2.9 on 2022-03-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220321_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocketCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mag_num', models.IntegerField()),
                ('defendant', models.CharField(max_length=50)),
                ('judge', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('code', models.CharField(max_length=40)),
                ('charge', models.CharField(max_length=200)),
                ('bond', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='date of court session')),
            ],
        ),
        migrations.CreateModel(
            name='DocketProceeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of court session')),
                ('judge', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='DocketCharge_new',
        ),
        migrations.DeleteModel(
            name='DocketProceeding_new',
        ),
    ]
