# Generated by Django 4.0.2 on 2022-03-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_docketproceeding_bond_set_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docketproceeding',
            name='bond_set_for',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
