# Generated by Django 3.2.9 on 2022-03-21 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220321_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='docketproceeding',
            name='mag_num',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.docketcharge'),
            preserve_default=False,
        ),
    ]
