# Generated by Django 4.0.4 on 2022-04-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_docketproceeding_mag_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='choice_id',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='response',
            name='row_id',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='responseoptions',
            name='choice_id',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='responseoptions',
            name='row_id',
            field=models.FloatField(default=0),
        ),
    ]
