# Generated by Django 3.2.9 on 2022-02-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_greeting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
