# Generated by Django 3.2.9 on 2022-03-21 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20220321_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocketCharge_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mag_num', models.IntegerField()),
                ('defendant', models.CharField(max_length=50)),
                ('judge', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('code', models.CharField(max_length=40)),
                ('charge', models.CharField(max_length=200)),
                ('bond', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='date of court session')),
            ],
        ),
        migrations.CreateModel(
            name='DocketProceeding_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of court session')),
                ('judge', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=5000)),
                ('mag_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.docketcharge_new')),
            ],
        ),
        migrations.RemoveField(
            model_name='docketproceeding',
            name='mag_num',
        ),
        migrations.DeleteModel(
            name='DocketCharge',
        ),
        migrations.DeleteModel(
            name='DocketProceeding',
        ),
    ]
