# Generated by Django 3.2.9 on 2022-03-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(choices=[('MUN', 'Municipal'), ('MAG', 'Magistrate'), ('CDC', 'Criminal')], default='MUN', max_length=3)),
                ('bail', models.IntegerField()),
                ('judge', models.CharField(choices=[('Municipal', (('Sens', 'Sens'), ('Jones', 'Jones'), ('Larche-Mason', 'Larche-Mason'), ('Shea', 'Shea'), ('Early', 'Early'), ('Landry', 'Landry'), ('Jupiter', 'Jupiter'))), ('Magistrate', (('Lombard', 'Lombard'), ('Collins', 'Collins'), ('Thibodeaux', 'Thibodeaux'), ('Blackburn', 'Blackburn'), ('Friedman', 'Friedman'))), ('Criminal', (('White', 'White'), ('Davillier', 'Davillier'), ('Willard', 'Willard'), ('Holmes', 'Holmes'), ('Goode-Douglas', 'Goode-Douglas'), ('Pittman', 'Pittman'), ('Campbell', 'Campbell'), ('Buras', 'Buras'), ('Herman', 'Herman'), ('Derbigny', 'Derbigny'), ('DeLarge', 'DeLarge'), ('Harris', 'Harris')))], default='Sens', max_length=80)),
                ('ethnicity', models.CharField(max_length=80)),
            ],
        ),
    ]
