# Generated by Django 3.2.9 on 2022-03-08 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_responses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
