# Generated by Django 4.0.3 on 2022-04-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_docketproceeding_bond_set_for'),
        ('website', '0008_auto_20220321_2234'),
    ]

    operations = [
    ]
