# Generated by Django 4.0.2 on 2022-03-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_question_responseoptions_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocketCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mag_num', models.IntegerField()),
                ('defendant', models.CharField(max_length=50)),
                ('judge', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('code', models.CharField(max_length=40)),
                ('charge', models.CharField(max_length=200)),
                ('bond', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='date of court session')),
            ],
        ),
        migrations.CreateModel(
            name='DocketProceeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mag_num', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='date of court session')),
                ('judge', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=5000)),
            ],
        ),
    ]
