# Generated by Django 3.2.9 on 2022-04-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_docketproceeding_bond_set_for'),
        ('website', '0008_auto_20220321_2234'),
    ]

    operations = [
    ]
