# Generated by Django 3.2.9 on 2022-03-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20220309_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='ada',
            field=models.CharField(default='yes', max_length=80),
        ),
        migrations.AddField(
            model_name='responses',
            name='afford',
            field=models.CharField(default='yes', max_length=80),
        ),
        migrations.AddField(
            model_name='responses',
            name='bond',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AddField(
            model_name='responses',
            name='housing',
            field=models.CharField(default='stable', max_length=80),
        ),
        migrations.AddField(
            model_name='responses',
            name='income',
            field=models.CharField(default='employed', max_length=80),
        ),
        migrations.AddField(
            model_name='responses',
            name='representer',
            field=models.CharField(default='OPD', max_length=80),
        ),
    ]
