# Generated by Django 4.0.3 on 2022-04-11 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_merge_20220411_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseoptions',
            name='survey_id',
        ),
        migrations.AddField(
            model_name='question',
            name='question_clean_text',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='responseoptions',
            name='survey',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.survey'),
        ),
    ]
