# Generated by Django 3.2.9 on 2022-03-13 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20220313_0139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='responses',
        ),
    ]
