# Generated by Django 4.0.4 on 2022-04-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_responseoptions_survey_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='choice_clean_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
