# Generated by Django 3.2.9 on 2022-03-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0011_delete_responses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(choices=[('MUN', 'Municipal'), ('MAG', 'Magistrate'), ('CDC', 'Criminal')], default='MUN', max_length=3)),
                ('bail', models.IntegerField()),
                ('judge', models.CharField(choices=[('Municipal', (('Sens', 'Sens'), ('Jones', 'Jones'), ('Larche-Mason', 'Larche-Mason'), ('Shea', 'Shea'), ('Early', 'Early'), ('Landry', 'Landry'), ('Jupiter', 'Jupiter'))), ('Magistrate', (('Lombard', 'Lombard'), ('Collins', 'Collins'), ('Thibodeaux', 'Thibodeaux'), ('Blackburn', 'Blackburn'), ('Friedman', 'Friedman'))), ('Criminal', (('White', 'White'), ('Davillier', 'Davillier'), ('Willard', 'Willard'), ('Holmes', 'Holmes'), ('Goode-Douglas', 'Goode-Douglas'), ('Pittman', 'Pittman'), ('Campbell', 'Campbell'), ('Buras', 'Buras'), ('Herman', 'Herman'), ('Derbigny', 'Derbigny'), ('DeLarge', 'DeLarge'), ('Harris', 'Harris'))), ("Don't know", "Don't know")], default='Sens', max_length=80)),
                ('ethnicity', models.CharField(max_length=80)),
                ('year', models.IntegerField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2021', max_length=4)),
                ('bond', models.CharField(default='0', max_length=80)),
                ('income', models.CharField(default='employed', max_length=80)),
                ('housing', models.CharField(default='stable', max_length=80)),
                ('representer', models.CharField(default='OPD', max_length=80)),
                ('ada', models.CharField(default='yes', max_length=80)),
                ('afford', models.CharField(default='yes', max_length=80)),
            ],
        ),
    ]
