# Generated by Django 3.2.9 on 2022-03-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_question_responseoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.BigIntegerField()),
                ('survey_year', models.IntegerField()),
                ('survey_name', models.CharField(max_length=100)),
                ('survey_use_start_date', models.IntegerField()),
                ('survey_use_end_date', models.IntegerField()),
                ('survey_phase_id', models.IntegerField()),
                ('survey_phase_venue_type', models.CharField(max_length=15)),
                ('survey_part_id', models.CharField(max_length=10)),
                ('survey_observation_level', models.CharField(max_length=15)),
                ('observer_type', models.CharField(max_length=40)),
                ('court_id', models.CharField(max_length=20)),
                ('survey_notes', models.CharField(max_length=40)),
            ],
        ),
    ]
