# Generated by Django 3.2.9 on 2022-03-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.BigIntegerField()),
                ('collector_id', models.BigIntegerField()),
                ('response_id', models.BigIntegerField()),
                ('response_text', models.CharField(max_length=5000)),
                ('question_id', models.BigIntegerField()),
                ('row_id', models.BigIntegerField(default=0)),
                ('choice_id', models.BigIntegerField()),
                ('other_id', models.BigIntegerField()),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
