# Generated by Django 4.0.2 on 2022-03-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_docketcharge_docketproceeding'),
        ('website', '0016_auto_20220313_2202'),
    ]

    operations = [
    ]
