# Generated by Django 4.0.2 on 2022-03-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_merge_20220315_0540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response_new',
        ),
    ]
